sudo: false
language: rust

addons:
  apt:
    packages:
      # Required for coveralls.
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev

rust:
  - stable
  - beta
  - nightly

env:
  global:
    # Do not use a separate feature flag for builds on the nightly compiler.
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""

before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

script:
  - |
      travis-cargo build &&
      travis-cargo test

matrix:
    allow_failures:
        - rust: nightly

after_success:
  - travis-cargo coveralls --no-sudo --verify
  # Workaround for https://github.com/huonw/travis-cargo/pull/55
  - ./kcov/build/src/kcov --verify --coveralls-id=$TRAVIS_JOB_ID --include-path=$TRAVIS_BUILD_DIR/src --exclude-path=$TRAVIS_BUILD_DIR/src/tests target/kcov target/debug/deps/pwm_lib-*
