[package]
name = "bdrck_params"
version = "0.2.0"
authors = ["Axel Rasmussen <axel.rasmussen1@gmail.com>"]

[dependencies]
backtrace = "0.2"
log = "0.3"

[dev-dependencies.bdrck_test]
path = "../bdrck_test"
